name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm --version

      - name: Install dependencies and build client
        run: |
          cd $GITHUB_WORKSPACE/client
          pnpm install --no-frozen-lockfile
          CI=false pnpm run build  # Ignore ESLint warnings

      - name: Install dependencies and build server
        run: |
          cd $GITHUB_WORKSPACE/server
          pnpm install --no-frozen-lockfile
          CI=false pnpm run build  # Ignore ESLint warnings

      - name: Archive production artifact
        uses: actions/upload-artifact@v3
        with:
          name: production-artifact
          path: |
            client/build
            server/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install pnpm and pm2 on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            if ! command -v pnpm &> /dev/null
            then
              curl -fsSL https://get.pnpm.io/install.sh | sh -
              export PATH="$HOME/.local/share/pnpm:$PATH"
              echo 'export PATH="$HOME/.local/share/pnpm:$PATH"' >> ~/.bashrc
            fi

            if ! command -v pm2 &> /dev/null
            then
              npm install -g pm2
            fi

      - name: Download production artifact
        uses: actions/download-artifact@v3
        with:
          name: production-artifact

      - name: Deploy to Linux machine
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            
            ls -al
            cd /var/wwww/
            cd client
            pnpm install
            pnpm run build
            cd ../server
            pnpm install
            pm2 delete 0 || true
            pm2 start pnpm --name decosta -- start
