name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Verify pnpm version
        run: pnpm --version

      - name: Install dependencies and build client
        run: |
          cd client
          pnpm install
          pnpm run build
        working-directory: client

      - name: Install dependencies and build server
        run: |
          cd ../server
          pnpm install
          pnpm run build
        working-directory: server

      - name: Archive production artifact
        uses: actions/upload-artifact@v3
        with:
          name: production-artifact
          path: |
            client/build
            server/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download production artifact
        uses: actions/download-artifact@v3
        with:
          name: production-artifact

      - name: Install pnpm on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            curl -fsSL https://get.pnpm.io/install.sh | sh
            export PATH="$HOME/.local/share/pnpm:$PATH"
            pnpm --version
            echo $PATH

      - name: Deploy to Linux machine
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /path/to/your/project
            cd client
            pnpm install
            pnpm run build
            cd ../server
            pnpm install
            pm2 delete 0 || true
            pm2 start pnpm --name decosta -- start
